Static resource tables
EtherealEngine/etherealengine pull request #7501
Opened 2023-01-27 00:06 UTC by barankyle

## Summary

_A summary of changes being made in this PR_

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-01-27 00:19 UTC, HexaField requested changes

2023-01-27 00:19 UTC, HexaField commented on packages/engine/src/scene/components/TypeComponent.ts
> +  onInit: () => '',
should return true

2023-03-09 01:58 UTC, speigg requested changes
So, generally, the idea is that whenever files are _tightly coupled_ to one another (e.g., uvol geometry data in .drcs and texture data in .mp4 ), or _interchangeable variants_ of one another (e.g., different encodings of the same content), they should be contained in a single resource. 

Each **Image** in the image table should point to a single image `resourceId`. 

Each **Volumetric** should contain a `thumbnailId` and a `resourceId`. 

Each **Model** should contain a `resourceId` (for it's model various files) a `thumbnailId` , and maybe later (if we find good workflows / use cases) additional resource ids for overriding materials or textures or whatnot. 

Each **Avatar** should contain a `resourceId`, a `thumbnailId`, a `modelId`, and possibly additional model id slots for accessories (hats, gloves, etc.). 

All of the other tables don't really have to be done in a single PR. It would be preferable to have a clean vertical slice that we can validate with an end-to-end workflow. 

Let's also make sure each static resource can be linked somehow to each project.

2023-03-09 01:58 UTC, speigg commented on packages/common/src/dbmodels/Image.ts
> +  jpegStaticResourceId?: string
this should just be `staticResourceId`

2023-03-09 01:58 UTC, speigg commented on packages/common/src/interfaces/AudioInterface.ts
> +  mpegStaticResourceId?: string
No reason for these to be separate static resources. An item in the audio table should point to a single static resource. That resource can be represented in a variety of formats / lods.

2023-03-09 01:58 UTC, speigg commented on packages/common/src/interfaces/ImageInterface.ts
> +  pngStaticResource?: StaticResourceInterface
Likewise here; each item in the image table should point to a single static resource.

2023-03-09 01:58 UTC, speigg commented on packages/common/src/interfaces/VideoInterface.ts
> +  thumbnail?: string
Same; each video should point to a single static resource

2023-03-09 01:58 UTC, speigg commented on packages/common/src/interfaces/VolumetricInterface.ts
> +  thumbnail?: string
`thumbnailResourceId`

2023-03-16 23:05 UTC, speigg approved these changes

2023-03-16 23:08 UTC, merged