tests(location): create location
EtherealEngine/etherealengine pull request #7775
Opened 2023-03-20 18:34 UTC by aditya-mitra

## Summary

Unit test for location service in server-core

## References

Refs https://github.com/EtherealEngine/etherealengine/issues/5997

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-03-25 01:08 UTC, HexaField requested changes

2023-04-07 02:51 UTC, HexaField requested changes

2023-04-07 02:51 UTC, HexaField commented on packages/server-core/src/social/location/location.class.ts
> +      if (location_settings) {
we can probably revert this

2023-04-07 03:36 UTC, aditya-mitra commented on packages/server-core/src/social/location/location.class.ts
> +      if (location_settings) {
reverted!

2023-04-07 04:12 UTC, HexaField approved these changes

2023-04-07 04:12 UTC, merged