Instanced LOD System
EtherealEngine/etherealengine pull request #7782
Opened 2023-03-21 22:07 UTC by dinomut1

BabylonJS has a more robust instanced LOD system that we will use as a basis. The difference between Babylon's instancing and the "thin" threejs instancing is detailed here: 
https://discourse.threejs.org/t/lod-instancing/20524/2

We will implement the more robust instancing and LOD system using a LODComponent and LODSystem that work together to keep track of each instance's distance from the camera, and switch different instanced LODs on and off based on said distance.

2023-04-04 23:41 UTC, HexaField requested changes

2023-04-04 23:41 UTC, HexaField commented on packages/engine/src/scene/functions/loaders/LODFunctions.ts
> +          model.updateMatrixWorld(true)
`model.updateMatrixWorld(true)` will call `model.updateMatrix()` internally

2023-04-05 00:18 UTC, HexaField requested changes

2023-04-05 00:18 UTC, HexaField commented on packages/engine/src/scene/SceneClientModule.ts
> +      type: SystemUpdateType.PRE_RENDER,
can be POST_RENDER

2023-04-08 18:46 UTC, 2dels approved these changes
Great job!

2023-04-12 03:43 UTC, merged