Model Transform + Avatar Improvements
EtherealEngine/etherealengine pull request #8053
Opened 2023-06-05 22:54 UTC by dinomut1

Add support for .gtlf avatar files with external dependencies
Add support for optimizing skinned meshes in model transform
Clean up material library

2023-06-05 23:06 UTC, barankyle approved these changes

2023-06-05 23:09 UTC, barankyle requested changes
Check-errors is flagging a usage of MaterialLibraryActions that's still hanging around.

2023-06-06 00:15 UTC, HexaField approved these changes

2023-06-06 09:44 UTC, HexaField approved these changes

2023-06-06 09:44 UTC, merged