fix(transform property): apply transformation to gizmo
EtherealEngine/etherealengine pull request #8213
Opened 2023-07-04 05:32 UTC by aditya-mitra

## Summary

Fixed gizmo updating when the right-hand transform inputs are changed.

## References

closes #7970 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-07-05 21:11 UTC, HexaField requested changes

2023-07-05 21:11 UTC, HexaField commented on .prettierignore
> +# /packages/projects/projects/**
Please revert

2023-07-05 21:11 UTC, HexaField commented on package.json
> +    "typescript": "5.0.2",
Please revert

2023-07-05 21:11 UTC, HexaField commented on package.json
> +    "bops": "^1.0.1",
Please revert

2023-07-06 06:21 UTC, aditya-mitra commented
Sorry. Accidentally committed the files with `git add .`

2023-07-07 02:29 UTC, HexaField requested changes
position and rotation looks good, but scaling with either the gizmo nor vector inputs do not show on the gizmo at all

2023-07-07 23:51 UTC, merged