Changes for channel-user service to use schema, knex & feathers 5
EtherealEngine/etherealengine pull request #8483
Opened 2023-08-17 09:17 UTC by MoizAdnan

## Summary

_A summary of changes being made in this PR_

## References

#7645, closes #8481 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-08-28 08:01 UTC, hanzlamateen requested changes

2023-08-28 08:01 UTC, hanzlamateen commented on packages/server-core/src/social/channel-user/migrations/20230817133703_channel-user.ts
> +    await knex.schema.createTable(channelUserPath, (table) => {
It should us `trx` here instead of `knex`

2023-08-28 15:12 UTC, MoizAdnan commented
@barankyle please approve this PR

2023-08-28 16:13 UTC, hanzlamateen requested changes

2023-08-28 16:13 UTC, hanzlamateen commented on packages/server-core/src/social/channel-user/channel-user.resolvers.ts
> +    const user = await context.app.service(userPath)._get(channelUser.userId)
There should be a null check here for `channelUser.userId` because migration file lists userId as defaults to null

2023-08-31 00:03 UTC, barankyle requested changes
I'm encountering errors when loading an existing channel and its messages. It seems that channel_users is not being populated on the channel when being returned from channel.find. The error technically isn't there, but a few front-end components like Message.tsx and FriendsMenu.tsx try to use a value from one of the channel users and fails because it's not there.

You can test this by opening two different Chrome profiles, going to the same location, then making those two users friends. Try to open the chat for both of them, it looks like the one who immediately accepted the friend request doesn't have this problem, but the one who sent the friend request does, and if either of them reload, they definitely can't open it because of this issue.

2023-09-05 21:34 UTC, barankyle requested changes
One minor thing I'm seeing now. When a chat between friends is open, the chat window is not immediately updating with new messages that others have sent. If I have two users as friends and they're sending messages to each other, the act of sending a message causes a re-fetch of the message history, but if the other person is sending messages, those new messages don't show up until the first user sends a message. The other person's messages should be filling in automatically as they're sent.

I do not see this issue on dev branch, so it seems this is a problem in this branch.

2023-09-07 00:23 UTC, barankyle approved these changes

2023-09-07 10:25 UTC, hanzlamateen approved these changes

2023-09-07 10:25 UTC, merged