Changes for project helper services to use schema, knex & feathers 5
EtherealEngine/etherealengine pull request #8508
Opened 2023-08-21 13:01 UTC by MoizAdnan

## Summary

_A summary of changes being made in this PR_

## References

#7645 #8507 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-09-01 17:46 UTC, barankyle approved these changes

2023-09-03 02:33 UTC, hanzlamateen requested changes

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-check-source-destination-match/project-check-source-destination-match.class.ts
> +export class ProjectCheckSourceDestinationMatchService implements ServiceInterface<any> {
Instead of any make this strictly typed.

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-check-source-destination-match/project-check-source-destination-match.hooks.ts
> +    find: [authenticate(), iff(isProvider('external'), verifyScope('projects', 'read') as any) as any],
Can we get rid of these as anys?

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-builder-tags/project-builder-tags.hooks.ts
> +    find: [authenticate(), iff(isProvider('external'), verifyScope('projects', 'read') as any) as any],
Get rid of these as any in this file and all other hook files created in this PR.

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-github-push/project-github-push.class.ts
> +    const project = await this.app.service('project').Model.findOne({
Can we replace this call with _get method?

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-build/project-build.class.ts
> +    return {} as ProjectBuildType
This shouldnt be there. Technically this method is returning void.

So this classes definition should be like:

`implements ServiceInterface<void, ProjectBuildPatch>`

We dont need `ProjectBuildType`

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-destination-check/project-destination-check.hooks.ts
> +    all: []
Resolvers for this service doesnot exists and they are not being called here.

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-github-push/project-github-push.class.ts
> +  async patch(id: NullableId, data: any, params?: RootParams): Promise<any> {
We dont need this any type here. It can be void

2023-09-03 02:33 UTC, hanzlamateen commented on packages/engine/src/schemas/projects/project-github-push.schema.ts
> +export const projectGithubPushPatchSchema = Type.Partial(Type.Object({ data: Type.Any() }), {
We dont need this schema here. This schema file can be just like: https://github.com/EtherealEngine/etherealengine/blob/62de622015cd5577c6f245c9576e1e118bd2e2cb/packages/engine/src/schemas/networking/instance-friends.schema.ts

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-github-push/project-github-push.resolvers.ts
> +export const projectGithubPushPatchResolver = resolve<ProjectGithubPushPatch, HookContext>({})
We do not need resolvers for this file as it wouldnt have any schema. for reference check `instance-friends` service in latest code.

2023-09-03 02:33 UTC, hanzlamateen commented on packages/server-core/src/projects/project-invalidate/project-invalidate.class.ts
> +      return await getStorageProvider(data.storageProviderName).createInvalidation([`projects/${data.projectName}*`])
We dont need this return statement. The class definition should implement:

`implements ServiceInterface<void, ProjectInvalidatePatch`

2023-09-04 09:20 UTC, hanzlamateen approved these changes

2023-09-04 12:41 UTC, merged