Changes for instance-active service to use schema, knex & feathers 5
EtherealEngine/etherealengine pull request #8626
Opened 2023-08-30 10:07 UTC by hurairahmateen

## Summary

_A summary of changes being made in this PR_

## References

#7645, #8623 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-08-31 17:40 UTC, barankyle approved these changes

2023-09-01 10:14 UTC, hanzlamateen requested changes

2023-09-01 10:14 UTC, hanzlamateen commented on packages/server-core/src/networking/instance-friends/instance-friends.class.ts
> +export class InstanceFriendsService implements ServiceInterface<InstanceInterface, InstanceFriendsParams> {
Why is `InstanceInterface` being used here? Why not `InstanceType`?

2023-09-01 10:35 UTC, hanzlamateen approved these changes

2023-09-01 10:38 UTC, merged