Changes for channel service to use schema, knex & feathers 5
EtherealEngine/etherealengine pull request #8666
Opened 2023-09-06 11:25 UTC by MoizAdnan

## Summary

_A summary of changes being made in this PR_

## References

#7645,  closes #8665 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-09-14 17:36 UTC, barankyle approved these changes

2023-09-15 06:57 UTC, hanzlamateen requested changes

2023-09-15 06:57 UTC, hanzlamateen commented on packages/server-core/src/social/channel/channel.class.ts
> +    if (channelUser.total < 0) throw new Error('Must be owner to delete channel')
It should be less than 1

2023-09-15 06:57 UTC, hanzlamateen commented on packages/server-core/src/social/channel/channel.hooks.ts
> +const applyInstanceIpAddressSort = async (context: HookContext, next: NextFunction) => {
We dont have data in sort, so we can remove it

2023-09-20 07:36 UTC, hanzlamateen approved these changes

2023-09-20 12:06 UTC, merged