feat(CI): speedup branch-build github action
EtherealEngine/etherealengine pull request #8735
Opened 2023-09-12 07:19 UTC by aditya-mitra

## Summary

Speedup branch-build github action by parallelizing jobs. This reduces the action time taken from 16 minutes to 5 minutes.

## References

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-09-12 07:20 UTC, HexaField commented
Brilliant!!!

2023-09-18 06:34 UTC, HexaField requested changes
we probably only need to run dev-docker or dev-reinit for `test`, not `build-client` or `check-errors`

2023-09-18 12:24 UTC, aditya-mitra commented
For `build-client` it would be required because: (the following would happen without running docker)
```
npm run build-client

> etherealengine@0.0.0 build-client
> cd packages/client && npm run build


> @etherealengine/client@1.4.0 build
> cross-env NODE_OPTIONS=--max_old_space_size=10240 vite build

[vite.config]: Failed to read clientSetting
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
    --------------------
    at Protocol._enqueue (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/Connection.js:116:18)
    at /Users/instinct/Desktop/etherealengine/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/Users/instinct/Desktop/etherealengine/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/Users/instinct/Desktop/etherealengine/node_modules/knex/lib/client.js:254:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}
[vite.config]: Failed to read coilSetting
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
    --------------------
    at Protocol._enqueue (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/instinct/Desktop/etherealengine/node_modules/mysql/lib/Connection.js:116:18)
    at /Users/instinct/Desktop/etherealengine/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/Users/instinct/Desktop/etherealengine/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/Users/instinct/Desktop/etherealengine/node_modules/knex/lib/client.js:254:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}
failed to load config from /Users/instinct/Desktop/etherealengine/packages/client/vite.config.ts
error during build:
TypeError: Cannot read properties of undefined (reading 'title')
    at /Users/instinct/Desktop/etherealengine/packages/client/vite.config.ts:998:30
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadConfigFromFile (file:///Users/instinct/Desktop/etherealengine/node_modules/vite/dist/node/chunks/dep-75f53616.js:66039:24)
    at async resolveConfig (file:///Users/instinct/Desktop/etherealengine/node_modules/vite/dist/node/chunks/dep-75f53616.js:65633:28)
    at async build (file:///Users/instinct/Desktop/etherealengine/node_modules/vite/dist/node/chunks/dep-75f53616.js:47803:20)
    at async CAC.<anonymous> (file:///Users/instinct/Desktop/etherealengine/node_modules/vite/dist/node/cli.js:822:9)
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @etherealengine/client@1.4.0
npm ERR!   at location: /Users/instinct/Desktop/etherealengine/packages/client
``` 

Similarly for `npm run check-errors`, we would require getting _initing_ the projects. (Following the is the output without running docker)

```
npm run check-errors

> etherealengine@0.0.0 check-errors
> lerna run --scope '@etherealengine/*' check-errors && lerna run --ignore '@etherealengine/*' check-errors

lerna notice cli v6.5.1
lerna verb rootPath /Users/instinct/Desktop/etherealengine
lerna WARN EWORKSPACES Workspaces exist in the root package.json, but Lerna is not configured to use them.
lerna WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.
lerna notice filter including "@etherealengine/*"
lerna info filter [ '@etherealengine/*' ]
lerna verb run Nx target configuration was not found. Task dependencies will not be automatically included.

    ✔  @etherealengine/xrui:check-errors (1s)
    ✔  @etherealengine/matchmaking:check-errors (2s)
    ✔  @etherealengine/common:check-errors (2s)
    ✔  @etherealengine/engine:check-errors (9s)
    ✔  @etherealengine/server-core:check-errors (9s)
    ✔  @etherealengine/ui:check-errors (11s)
    ✔  @etherealengine/server:check-errors (10s)
    ✔  @etherealengine/taskserver:check-errors (10s)
    ✔  @etherealengine/instanceserver:check-errors (10s)
    ✔  @etherealengine/client-core:check-errors (14s)
    ✔  @etherealengine/editor:check-errors (11s)
    ✔  @etherealengine/client:check-errors (13s)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target check-errors for 12 projects (1m)

lerna notice cli v6.5.1
lerna verb rootPath /Users/instinct/Desktop/etherealengine
lerna WARN EWORKSPACES Workspaces exist in the root package.json, but Lerna is not configured to use them.
lerna WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.
lerna notice filter excluding "@etherealengine/*"
lerna info filter [ '!@etherealengine/*' ]
lerna verb run Nx target configuration was not found. Task dependencies will not be automatically included.

    ✔  ee-bot:check-errors (8s)

    ✖  ee-development-test-suite:check-errors
       > ee-development-test-suite@0.0.0 check-errors
       > tsc --noemit

       examples/utils/avatar/simulateMovement.ts(63,35): error TS2339: Property 'elapsedSeconds' does not exist on type 'Engine'.
       npm ERR! Lifecycle script `check-errors` failed with error:
       npm ERR! Error: command failed
       npm ERR!   in workspace: ee-development-test-suite@0.0.0
       npm ERR!   at location: /Users/instinct/Desktop/etherealengine/packages/projects/projects/ee-development-test-suite

    ✔  eepro-ecommerce-tools:check-errors (12s)
    ✔  default-project:check-errors (15s)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target check-errors for 4 projects (15s)

    ✔    3/4 succeeded [0 read from cache]

    ✖    1/4 targets failed, including the following:
         - ee-development-test-suite:check-errors
```

2023-09-18 22:02 UTC, HexaField approved these changes

2023-09-19 05:45 UTC, merged