show thumbnail of scene on scene save as
EtherealEngine/etherealengine pull request #9339
Opened 2023-11-27 11:54 UTC by aditya-mitra

## Summary

Show the thumbnail of scene when the scene is saved as.

## References

## QA Steps

#### Earliier

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/8cafb0aa-2d84-4440-9ca3-d3f3584db6a9)

#### Now

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/6364be2f-e4ab-4699-9f82-659d09d9c07e)

2023-11-28 01:25 UTC, HexaField commented on packages/editor/src/components/EditorContainer.tsx
> +      const thumbnailBlob = await takeScreenshot(256, 160, 'jpeg')
we dont want to be taking two screenshots, we are able to display ktx2s as images

2023-12-11 04:43 UTC, HexaField requested changes
We should also include the thumbnail in the regular save menu.

2023-12-11 18:59 UTC, mrhegemon approved these changes

2023-12-12 00:54 UTC, mrhegemon approved these changes

2023-12-12 00:55 UTC, mrhegemon requested changes

2023-12-12 00:55 UTC, mrhegemon commented on packages/editor/src/functions/takeScreenshot.ts
> +  format = 'jpeg' as 'jpeg' | 'png',
Huh? Why these formats?

2023-12-12 04:33 UTC, aditya-mitra commented
> We should also include the thumbnail in the regular save menu.

Implemented!

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/efa229a9-5f30-4c12-b91e-b82511e998dd)

2023-12-12 04:46 UTC, HexaField approved these changes

2023-12-12 04:48 UTC, merged