Improve heap space usage
EtherealEngine/etherealengine pull request #9467
Opened 2023-12-18 19:58 UTC by DanielBelmes

## Summary

## References
closes #_insert number here_

## QA Steps

2023-12-20 18:51 UTC, DanielBelmes commented on dockerfiles/builder/Dockerfile-builder
> +FROM node:21-bookworm-slim as runner
@barankyle @HexaField It does work just fine as far as I can see but there might be some edge cases. Don't know if this is 100% necesarry for my changes though I did see some bugs with `packages/client/scripts/populate-assetlinks.ts` and node18 with my changes

2023-12-20 19:12 UTC, DanielBelmes commented
also would like to note this means dev will no longer have sourcemaps. If we want them in dev then there is a env var available. But we definitly don't want them in production like we've been doing.
@barankyle @speigg @HexaField

2023-12-20 20:00 UTC, DanielBelmes commented
note packages/client/scripts/populate-assetlinks.ts will be broken for the time being until we want to upload to Google Play Store

2023-12-20 20:11 UTC, HexaField commented
> note `packages/client/scripts/populate-assetlinks.ts` will be broken for the time being until we want to upload to Google Play Store

This is probably a deal breaker if it also breaks PWA support for Meta Quest store support

2023-12-20 20:31 UTC, barankyle commented
I don't see where we use this 

> > note `packages/client/scripts/populate-assetlinks.ts` will be broken for the time being until we want to upload to Google Play Store
> 
> This is probably a deal breaker if it also breaks PWA support for Meta Quest store support

I don't see that we currently use this anywhere. We don't publish anything to any store from what I can see.

2023-12-20 21:05 UTC, speigg commented
> also would like to note this means dev will no longer have sourcemaps. If we want them in dev then there is a env var available. But we definitly don't want them in production like we've been doing. @barankyle @speigg @HexaField

Can we (and do we want to) server source maps in separate files, so they only load when dev tools are open?

2023-12-20 21:07 UTC, speigg approved these changes

2023-12-20 21:07 UTC, speigg requested changes
Just some failing tests, but otherwise looks good!

2023-12-20 21:53 UTC, DanielBelmes commented
> > also would like to note this means dev will no longer have sourcemaps. If we want them in dev then there is a env var available. But we definitly don't want them in production like we've been doing. @barankyle @speigg @HexaField
> 
> Can we (and do we want to) serve source maps in separate files, so they only load when dev tools are open?

That's fairly easy as well. I think that's a good option.

2023-12-20 22:45 UTC, DanielBelmes commented
@speigg @HexaField looks like the errors are brought on by a circular dependency between Engine and XUI since I was moving to using assetLoader which lives in the engine currently. It's a decent save not having two ktx2loaders. Any ideas for a solution

2023-12-21 19:01 UTC, DanielBelmes commented
@HexaField @speigg All paths to fixing the cyclic dependencies lead us to considering larger architecture changes so I will shelve the single ktx2loader idea for now. We should return to it soon though.

2023-12-21 21:34 UTC, speigg approved these changes

2023-12-21 21:35 UTC, merged