Deprecate directional light useInCSM and add "primary light" option in scene renderer setting
EtherealEngine/etherealengine pull request #9590
Opened 2024-01-09 21:44 UTC by MichaelEstes

## Summary

## References
closes #9580 

## QA Steps

2024-01-10 00:19 UTC, HexaField requested changes

2024-01-10 00:19 UTC, HexaField commented on packages/editor/src/components/properties/RenderSettingsEditor.tsx
> +  for (const entity of DirectionalLightQuery()) {
we should use useQuery here instead of a standard query

2024-01-10 00:19 UTC, HexaField commented on packages/engine/src/renderer/WebGLRendererSystem.ts
> +    primaryLight: '',
should be typed as EntityUUID

2024-02-03 01:30 UTC, DanielBelmes commented
Would love to get this in as well if you can fix the conflicts when you're available.

2024-02-03 03:01 UTC, HexaField commented
> Would love to get this in if you can fix the conflicts when you're available.

This will break shadows for all our scenes, so we'll need to do it at a time that makes sense.

Otherwise, we could add a migration utility.

2024-02-03 03:27 UTC, DanielBelmes commented
> > Would love to get this in if you can fix the conflicts when you're available.
> 
> This will break shadows for all our scenes, so we'll need to do it at a time that makes sense.
> 
> Otherwise, we could add a migration utility.

Migration utility would be nice. It could live in the /studio page and it can parse all scene json in a project and apply a specific migration? We're gonna need something like a "recipe." It needs to detect the discrepancy and then find a solution for it. 

We can also do a migration commit and hope people resave their scenes and remove that logic at a later release. 

We can also detect the issue and instruct in the studio to fix it.

2024-04-01 23:13 UTC, HexaField commented
@MichaelEstes @DanielBelmes let's get this PR updated with the latest dev, i think we can easily add a migration script:

in `SceneState.loadScene` where our other migrations are, we should be able to very easily find the first directional light in the scene that has useInCSM enabled, and set the `primaryLight` value to that entity

2024-04-18 06:31 UTC, HexaField approved these changes

2024-04-18 06:46 UTC, merged